platform:ios, "11.0"
use_frameworks!
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] ='NO'
    end
  end
end


def shared_pods
	pod 'AFNetworking'
	pod 'YYKit'

end

target 'iOSBasic' do
	shared_pods
end

